### ISSUE TITLE
Incompatible with carpet 'hoppercounter'

### ISSUE THREAD

**Issue by MeeniMc** [lucaargolo/accurate-maps#8]
For some reason, when this mod is loaded, the carpet rule 'hopperCounter' doesn't work anymore.

**Comment by MeeniMc** [comment]
Let's be a bit more helpful with replication steps

MC 1.19.3
Accurate Maps 1.1-BETA+1.19 (self compiled from PR #6)
Carpet 1.4.93

1. Load a world
2. place a wool block, place a hopper pointing inside the wool block
3. type `/carpet hoppercounter true`
4. place items in the hopper
5. number of items doesn't decrease, counter doesn't count

**Comment by slushie0** [comment]
Is this a problem only with 1.19.3, or does this happen on every version of the mod?

**Comment by MeeniMc** [comment]
I didn't try with prior versions yet.

**Comment by MeeniMc** [comment]
I can replicate with 1.19.2 (using the gradlew runclient and adding carpet 1.4.84 by hand to the run/mods directory).

BTW the maven pulled Architectury (for REI runtime dependency) is bust.

**Comment by MeeniMc** [comment]
Maybe this https://github.com/lucaargolo/accurate-maps/blob/8fb8de5dfa7fc23e9ab5c4abd6ec7422a3942731/src/main/java/io/github/lucaargolo/accuratemaps/mixin/AbstractBlockStateMixin.java#L23
causes a problem w.r.t to https://github.com/gnembon/fabric-carpet/blob/23ed35a3983d1571ecdca03cc157b0d52b189071/src/main/java/carpet/mixins/HopperBlockEntity_counterMixin.java#L43

**Comment by slushie0** [comment]
Either way it would be nice if this could get pushed since I've been waiting a while to use this mod.

**Comment by MeeniMc** [comment]
Presumably resolved by patch on Carpet side. Will reopen if still present in 1.19.4/20 when mod updates.
